// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package shared

type UnionString string

func (UnionString) ImplementsAuthRuleConditionValueUnionParam() {}
func (UnionString) ImplementsAuthRuleConditionValueUnion()      {}
func (UnionString) ImplementsAuthRuleV2NewResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2NewResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2GetResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2GetResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2UpdateResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2UpdateResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2ListResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2ListResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2ApplyResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2ApplyResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2DraftResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2DraftResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2PromoteResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2PromoteResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2NewParamsBodyCreateAuthRuleRequestAccountTokensParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2NewParamsBodyCreateAuthRuleRequestCardTokensParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2NewParamsBodyCreateAuthRuleRequestProgramLevelParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionString) ImplementsAuthRuleV2DraftParamsParametersConditional3DsActionParametersConditionsValueUnion() {
}

type UnionInt int64

func (UnionInt) ImplementsAuthRuleConditionValueUnionParam() {}
func (UnionInt) ImplementsAuthRuleConditionValueUnion()      {}
func (UnionInt) ImplementsVelocityLimitParamsPeriodUnion()   {}
func (UnionInt) ImplementsAuthRuleV2NewResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2NewResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2GetResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2GetResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2UpdateResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2UpdateResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2ListResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2ListResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2ApplyResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2ApplyResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2DraftResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2DraftResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2PromoteResponseCurrentVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2PromoteResponseDraftVersionParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2NewParamsBodyCreateAuthRuleRequestAccountTokensParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2NewParamsBodyCreateAuthRuleRequestCardTokensParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2NewParamsBodyCreateAuthRuleRequestProgramLevelParametersConditional3DsActionParametersConditionsValueUnion() {
}
func (UnionInt) ImplementsAuthRuleV2DraftParamsParametersConditional3DsActionParametersConditionsValueUnion() {
}
